### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by TwitchyMcNutz** [Vae2009/ConRO_Priest#2]
Not sure if this is due to being level 1 and no spec set or possibly from being on the starting ship for Exile's Reach before there is even a map.  Picture of LUA error:  https://puu.sh/JsADK/a163a3d9b6.png

**Comment by TwitchyMcNutz** [comment]
Quick update.  Getting off the boat and onto the island with a map did not solve it.  Error repeats every time I enter combat.

**Comment by Vae2009** [comment]
That is definately due to the new talent system. It will go away as soon as you reach 10 and shouldn't be firing at all yet. odd.

**Comment by TwitchyMcNutz** [comment]
Yes, can confirm once I hit 10 and selected a spec then it started to work normally without the error.

**Comment by Vae2009** [comment]
Resolved
